swagger: "2.0"
info:
  title: AKS Engine
  version: 2.0.0-alpha
produces:
  - application/json
consumes:
  - application/json
schemes:
  - http
paths:
  /healthz:
    get:
      operationId: healthz
      summary: "API server health check"
      responses:
        200:
          description: API server is healthy
        default:
          description: unexpected error
  /v2/create:
    post:
      operationId: createCluster
      summary: "create a new Kubernetes cluster"
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: "#/definitions/createData"
      responses:
        200:
          description: create cluster response
          schema:
            $ref: "#/definitions/createData"
        default:
          description: unexpected error
          schema:
            $ref: "#/definitions/error"
securityDefinitions:
  basic:
    type: basic
definitions:
  createData:
    type: object
    properties:
      mgmtClusterKubeConfigPath:
        type: string
        minLength: 0
      subscriptionID:
        type: string
        minLength: 0
      tenantID:
        type: string
        minLength: 0
      clientID:
        type: string
        minLength: 0
      clientSecret:
        type: string
        minLength: 0
      azureEnvironment:
        type: string
        minLength: 0
      clusterName:
        type: string
        minLength: 0
      vnetName:
        type: string
        minLength: 0
      resourceGroup:
        type: string
        minLength: 0
      location:
        type: string
        minLength: 0
      controlPlaneVMType:
        type: string
        minLength: 0
      nodeVMType:
        type: string
        minLength: 0
      sshPublicKey:
        type: string
        minLength: 0
      kubernetesVersion:
        type: string
        minLength: 0
      controlPlaneNodes:
        type: integer
        minLength: 0
      nodes:
        type: integer
        minLength: 0
  error:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
