// Code generated by go-swagger; DO NOT EDIT.

// Package restapi AKS Engine
//
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 2.0.0-alpha
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
