// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// HealthzOKCode is the HTTP code returned for type HealthzOK
const HealthzOKCode int = 200

/*HealthzOK API server is healthy

swagger:response healthzOK
*/
type HealthzOK struct {
}

// NewHealthzOK creates HealthzOK with default headers values
func NewHealthzOK() *HealthzOK {

	return &HealthzOK{}
}

// WriteResponse to the client
func (o *HealthzOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*HealthzDefault unexpected error

swagger:response healthzDefault
*/
type HealthzDefault struct {
	_statusCode int
}

// NewHealthzDefault creates HealthzDefault with default headers values
func NewHealthzDefault(code int) *HealthzDefault {
	if code <= 0 {
		code = 500
	}

	return &HealthzDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the healthz default response
func (o *HealthzDefault) WithStatusCode(code int) *HealthzDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the healthz default response
func (o *HealthzDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WriteResponse to the client
func (o *HealthzDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(o._statusCode)
}
